### ISSUE TITLE
Support new Minecraft Version 1.15 and 1.16

### ISSUE THREAD

**Issue by mfilser** [RyanHecht/CommandBlockConverter#1]
Hello,
this project sounds very helpful. I tried today to install the plugin at my Minecraft Server 1.15.2, but got this exception on starting the Server again:
```
org.bukkit.plugin.UnknownDependencyException: BKCommonLib
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.15.2.jar:git-Paper-321]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-321]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-321]
```

Is there any change to get it working at Minecraft 1.15 and/or 1.16.

Thank you a lot in advance for your reply,
Best regards,
Martin

**Comment by RyanHecht** [comment]
Hey, you're free to work on it and submit a PR if you'd like! I likely won't be doing it myself, though

**Comment by mfilser** [comment]
Thank you a lot for your answer. I had a look to find informations what changed between the Minecraft versions, especially about commands, but didn't find a good documentation.
Maybe you have a hint for me ?

**Comment by GlitchTime** [comment]
Hey hey I know it's been like 5 years, however, if I'm right you're still active can you tell me how this works? because it isn't converting my commands.

**Comment by RyanHecht** [comment]
@GlitchTime 
> Hey hey I know it's been like 5 years, however, if I'm right you're still active can you tell me how this works? because it isn't converting my commands.

This only works for converting Minecraft version 1.8 commands to Minecraft version 1.12 commands. All you need to do is install this plugin (and [BKCommonLib](https://www.spigotmc.org/resources/bkcommonlib.39590/)) and load chunks! Any command blocks in those chunks will have their commands converted from the 1.8 syntax to the 1.12 syntax.

It doesn't support any other versions other than 1.8->1.12!
